# Generated by Django 4.0.4 on 2022-05-23 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_comment_c_date_alter_news_n_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='c_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 23, 14, 0, 36, 344770), null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='n_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 23, 14, 0, 36, 344770)),
        ),
    ]
